apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ypmtest
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: HelmCharts
    repoURL: 'https://gitlab.fintech.cht.com.tw/chtfintech/ypm-test'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
